name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - pandas
  - numpy
  # - scikit-learn
  - matplotlib
  - seaborn
  - pip:
    - statsmodels
